import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/providers";
import Navbar from "@/components/Navbar/Navbar";
import Pagination from "@/components/Pagination/Pagination";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Navbar/>
          <section className="px-[10vw] py-[2rem] bg-[#f3f6f6]">
            {children}
            <Pagination/>
          </section>
        </body>
      </Providers>
    </html>
  );
}
