import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/lib/providers";
import Navbar from "@/components/Navbar/Navbar";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-[#f3f6f6]">
      <Providers>
        <React.StrictMode>
          <body className="h-full bg-[#f3f6f6]">
            <Navbar />
            {children}
          </body>
        </React.StrictMode>
      </Providers>
    </html>
  );
}
